/**
 * proposal-replies.ts
 * Scans Apple Mail for Jonathan's replies to maintenance proposal emails
 * and applies the decisions (approve / keep / drop / undo).
 *
 * Subject patterns matched (case-insensitive, strips RE:/Fwd: prefixes):
 *   [maintenance:<proposal-id>] approve
 *   [maintenance:<proposal-id>] keep
 *   [maintenance:<proposal-id>] drop
 *   undo [maintenance:<proposal-id>]
 *   approve [maintenance:<proposal-id>]
 *   keep [maintenance:<proposal-id>]
 *   drop [maintenance:<proposal-id>]
 *
 * The "approve", "keep", "drop" keywords are matched from the mailto subject
 * that the briefing generates.  Jonathan can also just click the link — the
 * subject is pre-filled.
 */

import { writeFile } from 'fs/promises';
import { homedir }   from 'os';
import { join }      from 'path';
import { runOsascript } from '../utils/retry-osascript';
import { applyProposal, undoProposal, parseProposals } from './proposal';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Decision = 'approve' | 'keep' | 'drop' | 'undo';

interface ParsedReply {
  proposalId: string;
  decision:   Decision;
  date:       string;
  subject:    string;
}

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

function log(msg: string): void {
  process.stderr.write(`[proposal-replies] ${msg}\n`);
}

// ---------------------------------------------------------------------------
// Strip email thread prefixes from subject lines
// ---------------------------------------------------------------------------

function normaliseSubject(raw: string): string {
  // Strip RE:, Fwd:, Re:, FW: (any case, any number of occurrences)
  return raw.replace(/^(re|fwd?|fw):\s*/gi, '').trim();
}

// ---------------------------------------------------------------------------
// Parse a subject line into (proposalId, decision)
// Returns null if not a maintenance reply.
// ---------------------------------------------------------------------------

function parseSubject(subject: string): { proposalId: string; decision: Decision } | null {
  const s = normaliseSubject(subject).toLowerCase();

  // Pattern 1: undo [maintenance:<id>]
  const undoMatch = s.match(/^undo\s+\[maintenance:(proposal-[\w-]+)\]/);
  if (undoMatch) return { proposalId: undoMatch[1], decision: 'undo' };

  // Pattern 2: [maintenance:<id>] <decision>
  //   Subject line generated by briefing renderer looks like:
  //   "[maintenance:proposal-abc123] approve" etc.
  const bracketFirst = s.match(/^\[maintenance:(proposal-[\w-]+)\]\s*(approve|keep|drop)(!*\s*.*)?$/);
  if (bracketFirst) {
    const decision = bracketFirst[2] as Decision;
    return { proposalId: bracketFirst[1], decision };
  }

  // Pattern 3: <decision> [maintenance:<id>]
  //   approve [maintenance:proposal-abc123]
  const decisionFirst = s.match(/^(approve|keep|drop)(!?\s+)?\[maintenance:(proposal-[\w-]+)\]/);
  if (decisionFirst) {
    const decision = decisionFirst[1] as Decision;
    return { proposalId: decisionFirst[3], decision };
  }

  // Pattern 4: bare [maintenance:<id>] in subject with no keyword — skip
  return null;
}

// ---------------------------------------------------------------------------
// AppleScript: scan Sent + Inbox for matching subjects in last 7 days
// ---------------------------------------------------------------------------

async function isMailRunning(): Promise<boolean> {
  try {
    const { execSync } = await import('child_process');
    const out = execSync('osascript -e \'tell application "System Events" to (name of processes) contains "Mail"\'', { timeout: 5000 }).toString().trim();
    return out === 'true';
  } catch {
    return false;
  }
}

async function scanMailForReplies(): Promise<ParsedReply[]> {
  if (!(await isMailRunning())) {
    log('Mail.app not running — skipping reply scan (open Mail to enable)');
    return [];
  }
  const script = `
tell application "Mail"
  set cutoff to (current date) - 7 * days
  set output to ""

  repeat with acct in every account
    repeat with mb in every mailbox of acct
      try
        set mbName to name of mb
        if mbName is "Sent Messages" or mbName is "Sent" or mbName is "Sent Items" or mbName is "Inbox" or mbName is "INBOX" then
          set allMsgs to (every message of mb whose date received is greater than cutoff and subject contains "maintenance:")
          repeat with msg in allMsgs
            try
              set subj to (subject of msg) as string
              set d to date received of msg
              set yr to year of d as integer
              set mo to month of d as integer
              set dy to day of d as integer
              set dateStr to (yr as string) & "-" & text -2 thru -1 of ("0" & (mo as string)) & "-" & text -2 thru -1 of ("0" & (dy as string))
              set output to output & dateStr & "|||" & subj & linefeed
            end try
          end repeat
        end if
      end try
    end repeat
  end repeat

  return output
end tell`;

  const scriptPath = join(homedir(), 'briefing-data', 'proposal-scan.applescript');
  try {
    await writeFile(scriptPath, script, 'utf-8');
    const stdout = await runOsascript(scriptPath);
    const replies: ParsedReply[] = [];

    for (const line of stdout.trim().split('\n')) {
      if (!line.trim()) continue;
      const [date, subject] = line.split('|||');
      if (!subject) continue;

      const parsed = parseSubject(subject.trim());
      if (!parsed) continue;

      replies.push({
        proposalId: parsed.proposalId,
        decision:   parsed.decision,
        date:       date?.trim() ?? new Date().toISOString().slice(0, 10),
        subject:    subject.trim(),
      });
    }

    return replies;
  } catch (err: any) {
    log(`Mail scan failed: ${err.message} — skipping reply processing`);
    return [];
  }
}

// ---------------------------------------------------------------------------
// Deduplicate: keep only the MOST RECENT decision per proposal ID
// (in case Jonathan replied more than once)
// ---------------------------------------------------------------------------

function deduplicateReplies(replies: ParsedReply[]): ParsedReply[] {
  const latest = new Map<string, ParsedReply>();
  for (const r of replies) {
    const existing = latest.get(r.proposalId);
    if (!existing || r.date > existing.date) {
      latest.set(r.proposalId, r);
    }
  }
  return Array.from(latest.values());
}

// ---------------------------------------------------------------------------
// Map decision keyword → ProposalOutcome for applyProposal()
// ---------------------------------------------------------------------------

function decisionToOutcome(decision: Decision): 'approved' | 'rejected' | 'kept' {
  switch (decision) {
    case 'approve': return 'approved';
    case 'drop':    return 'rejected';
    case 'keep':    return 'kept';
    default:        return 'rejected';
  }
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Processes Jonathan's approval/rejection replies from Apple Mail.
 * Run at startup of both index.ts (every morning) and maintenance.ts (Sundays).
 * Non-fatal — logs and continues on any error.
 */
export async function processProposalReplies(): Promise<void> {
  try {
    log('scanning Apple Mail for proposal replies (last 7 days)...');
    const rawReplies = await scanMailForReplies();

    if (rawReplies.length === 0) {
      log('no proposal replies found');
      return;
    }

    const replies = deduplicateReplies(rawReplies);
    log(`found ${replies.length} unique proposal replies to process`);

    // Load currently pending proposals to avoid processing replies for already-resolved ones
    const pendingIds = new Set((await parseProposals()).map(p => p.id));

    for (const reply of replies) {
      const { proposalId, decision } = reply;
      log(`processing: ${proposalId} → ${decision} (from subject: "${reply.subject}")`);

      if (decision === 'undo') {
        await undoProposal(proposalId);
        log(`undo applied for ${proposalId}`);
        continue;
      }

      // For approve/keep/drop, only act if still pending (avoid double-processing)
      if (!pendingIds.has(proposalId)) {
        log(`${proposalId} not in pending list — already processed or not found, skipping`);
        continue;
      }

      const outcome = decisionToOutcome(decision);
      await applyProposal(proposalId, outcome);
      log(`applied ${outcome} for ${proposalId}`);
    }

    log('reply processing complete');
  } catch (err: any) {
    log(`processProposalReplies error: ${err.message} — continuing`);
  }
}
